[package]
name = "miniredis"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "miniredis-server"
path = "src/bin/server.rs"

[[bin]]
name = "miniredis-client"
path = "src/bin/client.rs"

[dependencies]
